[package]
name = "ambra-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
futures-util = "0.3.33"
qbz-models = { git = "https://github.com/vicrodh/qbz.git", rev = "93ae499f38835dc7c110ebaa07a49da5c714f1f9" }
qbz-qobuz = { git = "https://github.com/vicrodh/qbz.git", rev = "93ae499f38835dc7c110ebaa07a49da5c714f1f9" }
reqwest = { version = "0.13.4", features = ["stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tidlers = "0.5.0"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.0", features = ["cors"] }
urlencoding = "2"
