[package]
name = "AMBRA"
version = "0.1.0"
description = "Ambra music player"
authors = ["Quantium Labs"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "ambra_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lofty = "0.24"
walkdir = "2"
base64 = "0.22"
tauri-plugin-window-state = "2"
oxideav-core = "0.1"
oxideav-flac = "0.0.11"
libc = "0.2"
souvlaki = "0.8.3"
symphonia = { version = "0.6", features = ["all"] }
crossbeam-channel = "0.5"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.1"
objc = "0.2.7"
coreaudio-rs = "0.13"

[target.'cfg(target_os = "windows")'.dependencies]
wasapi = "0.22"
